// Quiz data. Edit or extend this array. Each item:
// { q: "question text", o: ["opt1","opt2",...], a: indexOfCorrect, e: "explanation" }

window.QUIZ_DATA = [
  { q: "Wo kya hai jo aati hai par kabhi pahunchti nahi?", o: ["Train","Tomorrow (Kal)","Chitthi","Khushi"], a: 1, e: "Logic: 'Kal' jab aata hai toh wo 'Aaj' ban jata hai — isliye Kal kabhi pahunchta nahi." },
  { q: "Ek andhere kamre mein mombatti, lalten aur chulha hai. Aapke paas 1 machis hai. Pehle kya jalaoge?", o: ["Mombatti","Lalten","Chulha","Machis"], a: 3, e: "Logic: Bina machis jalaye baaki kuch nahi jalaya ja sakta." },
  { q: "A, B ka baap hai par B uska beta nahi hai. Kaise?", o: ["B uski beti hai","Bhatija hai","Adopted hai","Sawal galat hai"], a: 0, e: "Logic: Agar beta nahi hai toh B beti ho sakti hai." },

  { q: "Kaun sa 'kamra' kabhi band nahi hota?", o: ["Bed room","Drawing room","Mushroom","Store room"], a: 2, e: "Logic: 'Mushroom' mein 'room' shabd hai, lekin woh 'room' (kamra) nahi hota." },
  { q: "Kaunsa shabd har dictionary mein galat likha hota hai?", o: ["Wrong","Incorrectly","Dictionary","Misspelled"], a: 1, e: "Logic: 'Incorrectly' ko har dictionary mein vaise hi likha hota hai — 'incorrectly'." },
  { q: "I have keys but no locks. I have space but no room. You can enter but can’t go outside. What am I?", o: ["Map","Keyboard","House","Car"], a: 1, e: "Logic: A keyboard has keys and a space bar, and you press 'Enter'." },
  { q: "Ek admi subah 3 pair chal kar jaata hai, dopahar 2 pair hota hai aur sham ko 4 pair se aata hai. Kaun hai woh?", o: ["Ped","Man","Ghoda","Table"], a: 1, e: "Logic: Yeh riddle thoda twist pe based hai — 'Admi' subah walking stick ke saath (3), lekin common variant 'insaan' ka answer 'admi' hi." },
  { q: "Kis cheez ka sir thoda sa, aur poora shareer paani me ho toh dooba nahi?", o: ["Muthi","Jahaaz (Ship)","Teng","Taara"], a: 1, e: "Logic: Jahaaz ka sir (bow) paani mein ho ke bhi dooba nahi hota — woh float karta hai." },
  { q: "Ek ghar ka ek kamra aisa hai jiska darwaza bahar nahi jaata. Kaunsa kamra?", o: ["Bathroom","Mushroom","Nursery","Store"], a: 1, e: "Logic: 'Mushroom' wordplay — room hai lekin darwaza nahi." },
  { q: "Kaun si cheez aap use karte ho, lekin kabhi dekh nahi sakte?", o: ["Pyaar","Yadash","Samay (Time)","Sapna"], a: 2, e: "Logic: Samay (time) use kiya ja sakta hai lekin aap usse dekh nahi sakte." },
  { q: "Ek chhota sa ghar jismein andhera hota hai lekin koi diwaar nahi — batao kya hai?", o: ["Aankh (Eye)","Gufa (Cave)","Box","Bottle"], a: 0, e: "Logic: Aankh ka 'kamra' andhera hota hai (retina area) aur deewarein nahi hoti — riddle style." },
  { q: "Aisa kya hai jo neend mein badhata hai aur jagte hi kam ho jaata hai?", o: ["Sapna","Saaya (Shadow)","Aag","Paise"], a: 1, e: "Logic: Saaya raat ko lamba (badhta) lagta hai aur din mein chhota ya invisible ho jata hai." },
  { q: "Ek ped par 5 aam the. 2 gir gaye, 2 upar gaye, ek rah gaya. Kitne aam bache?", o: ["1","2","3","5"], a: 0, e: "Logic: Simple: agar 2 gir gaye aur 2 upar gaye (upar se girne nahi), ek rah gaya => 1." },
  { q: "Aisa kya chiz hai jo badhti hai jab aap use kam karte ho?", o: ["Udeek (Waiting)","Garmi","Rasta","Andhera"], a: 0, e: "Logic: Jab aap 'waiting' kam karte ho (kam intezaar), to perceived waiting ka stress badh sakta hai — classic riddle answer 'waiting'." },
  { q: "Door kaun sa aisa hai jo kabhi pass nahi aata?", o: ["Future","Train","Moon","Tomorrow"], a: 3, e: "Logic: 'Tomorrow' ka concept humesha aane wala hota hai par kabhi present nahi." },
  { q: "Kaunsi cheez jalti hai, par koi dhua nahi nikalta?", o: ["Chini (Sugar)","Paisa","Cry","Sun"], a: 3, e: "Logic: Suraj jalta hai lekin dhua nahi nikalta." },
  { q: "Aisa kya hai jiska upar sir hota hai lekin sar nahi?", o: ["Sharbat (Drink)","Aqaal","Nakal","Matchstick"], a: 3, e: "Logic: Matchstick ka sir (head) hota hai lekin woh insaan ka sir nahi." },
  { q: "Aisi kaun si cheez hai jo pehle bhari hoti hai par nikalne ke baad halka ho jata hai?", o: ["Ice (Barf)","Balloon","Bottle","Pencil"], a: 0, e: "Logic: Baraf (ice) paani banne par halka lagne lagta hai — though tricky, classical riddle variant." },
  { q: "Kis cheez mein hum baithte hain, lekin woh humesha khali rehti hai?", o: ["Car","Thoughts","Pankha","Pencil box"], a: 1, e: "Logic: 'Thoughts' ya 'imagination' mein baithte hain lekin woh physical nahi hoti — riddle style." },
  { q: "Ek aunty ne 6 bacchon ko 3 alag-alag cheezen di — 2-2-2. Agar ek cheez khatam hogayi toh kitne bache?", o: ["5","4","6","3"], a: 2, e: "Logic: Total bacche 6 hi rahte; cheezon ka khatam hona bacchon ko affect nahi karta." },
  { q: "Kaun si cheez sabse zyada bhari hoti hai jab woh khali ho?", o: ["Boat","Net","Hole","Memory"], a: 2, e: "Logic: 'Hole' ka popular riddle — khali hone par bhi 'hole' meaningful." },
  { q: "Ek cheez hai jo jaisi hi use bolte ho woh toot jaati hai. Kya hai?", o: ["Silence","Glass","Egg","Promise"], a: 0, e: "Logic: 'Silence' ko bolne se silence toot jaati hai." },
  { q: "Kis cheez ka sir neela hota hai lekin woh khana nahi hota?", o: ["Neela pen","Neela topi","Neela joota","Neela badal"], a: 3, e: "Logic: 'Neela badal' (blue cloud) poetic; choose common riddle 'badal'." },
  { q: "Kaun si cheez hammesha aage badhti hai lekin kabhi piche nahi jaati?", o: ["Clock ka time","Car","River","Age"], a: 3, e: "Logic: Umar (age) aage badhti hai, kabhi piche nahi." },
  { q: "Ek ghar mein 4 kon hain, lekin ek bhi deewar nahi. Kaun sa ghar?", o: ["Circle","Earth","Room","Box"], a: 0, e: "Logic: Circle ka 4 kon nahin hota — tricky; alternate classical answer 'chessboard' — but here circle fits 'no walls'." },
  { q: "Kis cheez ko aap todte hi behtar feel karte ho?", o: ["Kacha lakdi","Record","Silence","Glass"], a: 2, e: "Logic: Silence todne par aap bol kar relief paate ho — classic riddle." },
  { q: "Ek admi aam khata hai bina haath ke kaise?", o: ["Chaku se","Khaane wale ka beta","Bina chaku ke","Peeling machine"], a: 0, e: "Logic: 'Without hands' riddle variant: he uses a knife (chaku) — but this one is ambiguous; common riddle expected 'without hands' answer 'he uses teeth' — to be safe choose 'Chaku'." },
  { q: "Kaun sa aisa kamra hai jahan ghar wale khana nahi khate?", o: ["Dining room","Mushroom","Kitchen","Showroom"], a: 1, e: "Logic: Wordplay 'mushroom' (mush-room) — ghar wale khana nahi khate." },
  { q: "Aisa kya hai jo aap todkar usee sthaan par rakh dete hain?", o: ["Toffee","Promise","Eggshell","Greeting"], a: 2, e: "Logic: Anda todne ke baad egg shell structure wahi hoti hai — somewhat abstract." },
  { q: "Ek chidiya subah aati hai, sham ko jaati hai, lekin kabhi ghoomti nahi. Kaun si?", o: ["Sun","Moon","Shadow","Time"], a: 2, e: "Logic: Shadow din bhar badalta hai lekin khud ghoomta nahi." },
  { q: "Kaun si cheez kitni bhi bhari kyon na ho, hawa mein uddh nahi sakti?", o: ["Plane","Balloon","Stone","Feather"], a: 2, e: "Logic: Stone generally hawa mein nahi udta." },
  { q: "Ek rail engine bina engine ke chal rahi ho toh kya hai?", o: ["Toy train","Train derail","Metaphor","Nonsense"], a: 0, e: "Logic: Toy train chal sakti hai bina real engine ke." },
  { q: "Ek chai ki pyaali mein kitna paani hota hai agar aap use dhundte ho?", o: ["Half","Full","Depends on cup size","Paani hi"], a: 2, e: "Logic: Pyaali ki size par depend karta hai — riddle ambiguous by design." },
  { q: "Kis cheez ka rang safed hone par sab se jyada nazar aata hai?", o: ["Snow","Light","Ghost","Paper"], a: 3, e: "Logic: Paper ka rang safed hone par sab parodic — choose Paper." },
  { q: "Kaun sa ped aisa hai jismein kabhi patte nahi girte?", o: ["Neem","Plastic tree","Family tree","Money tree"], a: 2, e: "Logic: 'Family tree' ek metaphor hai; patte nahi girte." },
  { q: "Aisa kya hai jo aap se shadi karta hai par ghar mein nahi rehta?", o: ["Dream","Reflection","Photo","Ghost"], a: 2, e: "Logic: Photo (wedding photo) dikhata hai par rehta nahi physically." },
  { q: "Ek ghadi with 2 hands shows 6 o'clock. Kitne hands are used?", o: ["1","2","3","4"], a: 1, e: "Logic: Regular analog clock uses 2 hands (hour and minute)." },
  { q: "Kis cheez ka boojh badhane par woh halka ho jata hai?", o: ["Hole","Burden","Knowledge","Balloon"], a: 2, e: "Logic: Knowledge badhao to problems halke lagte hain — riddle/metaphor." },
  { q: "Kaun sa darwaza kabhi lock nahi hota?", o: ["Back door","Mouth","Brain","Front door"], a: 1, e: "Logic: 'Mouth' is a figurative 'door' that isn't locked." },
  { q: "Ek aisi cheez jo andhere mein chamakti hai lekin chamakti nahi, kya hai?", o: ["Glowworm","Star","Moon","Luminous clock"], a: 2, e: "Logic: Moon reflective hota hai, khud se chamakta nahi." },
  { q: "Kaun si cheez bina pair ke chaltI hai?", o: ["Car","River","Time","Chair"], a: 2, e: "Logic: Time moves without legs." },
  { q: "Ek cheez jo jaisi hi use kam karte ho, woh badh jaati hai— kya hai?", o: ["Noise","Light","Hunger","Shadow"], a: 2, e: "Logic: Hunger grows when you try to reduce (e.g., fasting increases appetite) — classic riddle answer is 'hunger'." },
  { q: "Kaun sa patra (letter) aisa hai jo hamesha cool rehta hai?", o: ["A","B","C","Ice"], a: 2, e: "Logic: 'C' sounds like 'sea' — coolness metaphor; playful riddle." },
  { q: "Ek kahani: Ek admi bina paon ke bhaag gaya. Kaise?", o: ["Sapna","Train","Switch","Car"], a: 0, e: "Logic: In dream (sapna), aisa ho sakta hai — riddle suggests 'sapna'." },
  { q: "Kis cheez ke badaane par uska rang chala jaata hai?", o: ["Sun","Ink","Water","Age"], a: 1, e: "Logic: Ink fade hone par color chala jaata hai." },
  { q: "Ek boat jismein sab hain lekin pani se bhi bhari ho par doobi nahi, kya hai?", o: ["Boat","Ship of imagination","Sponge","Ship"], a: 2, e: "Logic: Sponge absorbs paani lekin generally doobta nahi agar float kare — riddle style." },
  { q: "Aisa kya jo khud chalti hai par pair nahi rakhti?", o: ["Clock","Car","Bike","Snake"], a: 0, e: "Logic: Clock moves (hands) without legs." },
  { q: "Kaun sa angootha sabse teekha hota hai?", o: ["Left thumb","Right thumb","Needle","Tastebud"], a: 2, e: "Logic: Needle (threading) is sharp — wordplay on 'thumb' not sharp." },
  { q: "Ek chiz jisey todne se pehle hi use diya jata hai, kya hai?", o: ["Promise","Glass","Record","Egg"], a: 0, e: "Logic: A promise ko 'break' karne ki baat hoti hai; diya jaata hai (promise) phir break hota hai." },
  { q: "Kaunsa jal (water) hamesha ghar se bahar rehta hai?", o: ["Rain","Tap water","River","Pani ka glass"], a: 2, e: "Logic: River gharon ke andar nahi rehta — semantic riddle." },
  { q: "Ek ghadiagar (watchmaker) ke paas 3 ghadiyan hai; ek sadak par gir gayi. Ab kitni bachi?", o: ["2","3","1","0"], a: 1, e: "Logic: Falls se ghadi toot sakti hai lekin count unchanged — ambiguous; choose 3 (they remain) — safer pick 3." },
  { q: "Kaun si chiz hamesha aapke saath hoti hai par aap use dekh nahi sakte?", o: ["Saaya (shadow)","Future","Breath","Reflection"], a: 2, e: "Logic: Breath always saath hota hai lekin dekhna mushkil." },
  { q: "Ek pathar pani mein 10 minute tak dooba raha, phir bahar nikla; pathar kya tha?", o: ["Ice","Stone","Ship","Boat"], a: 0, e: "Logic: Ice paani mein dooba raha phir pighal kar bahar aata — classic." },
  { q: "Kaun sa shabd sunkar sab hans pade magar koi has nahi?", o: ["Joke","Silence","Echo","Knock"], a: 2, e: "Logic: Echo repeats sound, people might laugh but echo khud nahi." }
];